name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

# https://tea.xyz/what-is-this-file
---
version: 1.0.0
codeOwners:
  - '0x9C3371B922b9Da7b6a5cd5daA738b03278f80f11'
quorum: 1
